server:
  port: 9003

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_bike_db?currentSchema=rental
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none   # turn off auto DDL since we’ll run scripts manually
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      default_schema: rental

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/